#!/bin/sh

start() {
	load_hisilicon -i
  modprobe tun
  echo "disabling wdt"
  insmod /lib/wdt.ko
  rmmod /lib/wdt.ko
}

stop() {
	load_hisilicon -r
}

restart() {
	stop
	sleep 1
	reload
}

case "$1" in
	start|stop)
		"$1";;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac
