#!/bin/sh

start() {
  
	load_hisilicon -i
	modprobe tun
	#modprobe rt2800usb
  #modprobe mt7601u
	#/root/vdec &	
}

stop() {
	load_hisilicon -r
}

restart() {
	stop
	sleep 1
	reload
}

case "$1" in
	start|stop)
		"$1";;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac
